spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:

      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
    generate-ddl: false

  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
    h2.console.enabled: true

server:
  error:
    include-message: always
  port: 8080