create table CAR (
                     ID bigint generated by default as identity,
                     NAME varchar(255),
                     primary key (ID)
);

create table DATE_AND_PRICE (
                                ID bigint generated by default as identity,
                                DATE timestamp,
                                PRICE double,
                                CAR_ID bigint,
                                PARKING_PLACE_ID bigint,
                                primary key (ID)
);

create table PARKING_PLACE (
                               ID bigint generated by default as identity,
                               primary key (ID)
);

alter table DATE_AND_PRICE
    add constraint CAR_FK
        foreign key (CAR_ID)
            references CAR;

alter table DATE_AND_PRICE
    add constraint PARKING_PLACE_FK
        foreign key (PARKING_PLACE_ID)
            references PARKING_PLACE;